# name of the software
name: Scribbler
baseurl: ""
theme: jekyll-theme-architect
description: JavaScript Notebook in the Browser for Easy Experimentation.
#project:
#  version: 1.0.0
#  download_url: https://github.com/gopi-suvanam/scribbler/archive/refs/heads/main.zip
#  download_text: Download

license:
  software: MIT License
  software_url: https://github.com/gopi-suvanam/scribbler/blob/main/LICENSE

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title: 'Blog'
      #icon: play
      #github
      brand: false
      url: https://scribbler.live/blog/
      
    - title: ''
      icon: play
      #github
      brand: false
      url: https://app.scribbler.live
      #https://github.com/gopi-suvanam/scribbler/
    - title: ''
      icon: github
      #github
      brand: true
      url: https://github.com/gopi-suvanam/scribbler/
      #https://github.com/gopi-suvanam/scribbler/
    - title: ''
      icon: download
      #github
      brand: false
      url: https://github.com/gopi-suvanam/scribbler/archive/refs/heads/main.zip
      #https://github.com/gopi-suvanam/scribbler/
  homepage:
    - title: Start (No Login)
      icon: play
      brand: false
      url: https://app.scribbler.live/#./examples/Hello-world.jsnb
    - title: Join Discord
      icon: discord
      brand: true
      url: https://discord.com/invite/uxNSsWunwU
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/gopi-suvanam/scribbler/
    - title: Issues
      icon: bug
      url: https://github.com/gopi-suvanam/scribbler/issues

ui:
  mode: 'auto' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#555"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    
    dark:
      color1: "#062a48"
      color2: "#304e67"
      trianglify: true
    light:
      color1: "#ffcd08"
      color2: "#ffcd08"
      trianglify: false
  masthead:
    color:
      dark: "#fede02"
      light: "#555"
    align:
      homepage: 'center'
      page: 'left'
    


social:
  github:
    user: gopi-suvanam
    repo: scribbler

pagination:
  enabled: true
  per_page: 10

paginate: 10
paginate_path: ./blog/page:num/

#analytics:
#  google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-docs-theme.gemspec
  - LICENSE.md
  - README.md
  - screenshot.png

plugins:
  - jekyll-sitemap
